server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weight?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    path match:
      matching-strategy: ant_path_matcher
#Oracle
#  driver-class-name: oracle.jdbc.driver.OracleDriver
#  datasource.url: jdbc:oracle:thin:@localhost:1521/WXS
#  username: wxs
#  password: 1234

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml #扫描mapper下的所有xml文件
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




