server:
  port: 9090
  ssl:
    key-store: classpath:server.pkcs12
    key-store-password: 123456
    keyStoreType: pkcs12
    enabled: true
  servlet:
    context-path: /api

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/weight?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: 1234
#    driver-class-name: com.mysql.cj.jdbc.Driver

  #SQL SERVER
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://172.16.18.63:1433;databaseName=WEIGHT;trustServerCertificate=true;rewriteBatchedStatements=true
      username: sa
      password: Root1234

  mvc:
    path match:
      matching-strategy: ant_path_matcher


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml #扫描mapper下的所有xml文件
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




